# Project
modVersion=0.0.1
mavenGroup=com.github.teamfossilsarcheology.fossils-archeology-rebirth
archivesName=fossils-archeology-rebirth

# Minecraft target
minecraftVersion=26.3

# Mod options
modId=fossil
modName=Fossils and Archeology Rebirth
modTeam=gemdYT
modLicense=Code: Mit, Assets: ARR
modDescription=Fabric 26.3 prehistoric animals, fossil incubation, archaeology, museum displays, and exploration.

# Dependencies
fabricLoaderVersion=0.19.5
fabricApiVersion=0.161.0+26.3
geckoLibVersion=5.5.7
geckoLibVersionId=kSxHvs99
terraBlenderVersion=26.3.0.0.9
terraBlenderVersionId=xirJYe1V
energyVersion=5.0.0
smartBrainLibVersion=2.0.2
smartBrainLibVersionId=i5vOn6hO
structurePoolApiVersion=1.3.0+26.3-fabric
structurePoolApiVersionId=Zxs162Py


org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.daemon=true
